### ISSUE TITLE
crash - meecreeps-1.12-1.1.0

### ISSUE THREAD

**Issue by Ioandar** [McJty/MeeCreeps#33]
related to berrybushes?

---- Minecraft Crash Report ----

WARNING: coremods are present:
  CoreMod (Aroma1997Core-1.12.2-1.3.0.2.jar)
  OpenModsCorePlugin (OpenModsLib-1.12.2-0.11.4.jar)
  Inventory Tweaks Coremod (InventoryTweaks-1.63.jar)
  IELoadingPlugin (ImmersiveEngineering-0.12-75-core.jar)
  ForgelinPlugin (Forgelin-1.6.0.jar)
  AstralCore (astralsorcery-1.12.2-1.8.4.jar)
  LoadingPlugin (RandomThings-MC1.12.2-4.0.8.jar)
  CTMCorePlugin (CTM-MC1.12-0.2.3.9.jar)
Contact their authors BEFORE contacting forge

// Hi. I'm Minecraft, and I'm a crashaholic.

Time: 1/11/18 3:14 PM
Description: Ticking entity

java.lang.IllegalArgumentException: Cannot get property PropertyBool{name=decayable, clazz=class java.lang.Boolean, values=[true, false]} as it does not exist in BlockStateContainer{block=natura:overworld_berrybush_raspberry, properties=[age]}
	at net.minecraft.block.state.BlockStateContainer$StateImplementation.func_177229_b(BlockStateContainer.java:201)
	at mcjty.meecreeps.actions.workers.ChopTreeActionWorker.findLeaves(ChopTreeActionWorker.java:59)
	at mcjty.meecreeps.actions.workers.ChopTreeActionWorker.harvest(ChopTreeActionWorker.java:38)
	at mcjty.meecreeps.actions.workers.ChopTreeActionWorker.lambda$tick$0(ChopTreeActionWorker.java:128)
	at mcjty.meecreeps.actions.workers.ChopTreeActionWorker$$Lambda$1669/1721979849.accept(Unknown Source)
	at mcjty.meecreeps.actions.workers.WorkerHelper.navigateTo(WorkerHelper.java:399)
	at mcjty.meecreeps.actions.workers.ChopTreeActionWorker.tick(ChopTreeActionWorker.java:128)
	at mcjty.meecreeps.actions.workers.WorkerHelper.tick(WorkerHelper.java:506)
	at mcjty.meecreeps.entities.MeeCreepWorkerTask.func_75246_d(MeeCreepWorkerTask.java:69)
	at net.minecraft.entity.ai.EntityAITasks.func_75774_a(SourceFile:129)
	at net.minecraft.entity.EntityLiving.func_70626_be(EntityLiving.java:763)
	at net.minecraft.entity.EntityLivingBase.func_70636_d(EntityLivingBase.java:2350)
	at net.minecraft.entity.EntityLiving.func_70636_d(EntityLiving.java:577)
	at net.minecraft.entity.EntityLivingBase.func_70071_h_(EntityLivingBase.java:2170)
	at net.minecraft.entity.EntityLiving.func_70071_h_(EntityLiving.java:295)
	at net.minecraft.world.World.func_72866_a(World.java:1990)
	at net.minecraft.world.WorldServer.func_72866_a(WorldServer.java:831)
	at net.minecraft.world.World.func_72870_g(World.java:1952)
	at net.minecraft.world.World.func_72939_s(World.java:1756)
	at net.minecraft.world.WorldServer.func_72939_s(WorldServer.java:612)
	at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:765)
	at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:666)
	at net.minecraft.server.integrated.IntegratedServer.func_71217_p(IntegratedServer.java:185)
	at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:524)
	at java.lang.Thread.run(Thread.java:745)

A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Head --
Thread: Server thread
Stacktrace:
	at net.minecraft.block.state.BlockStateContainer$StateImplementation.func_177229_b(BlockStateContainer.java:201)
	at mcjty.meecreeps.actions.workers.ChopTreeActionWorker.findLeaves(ChopTreeActionWorker.java:59)
	at mcjty.meecreeps.actions.workers.ChopTreeActionWorker.harvest(ChopTreeActionWorker.java:38)
	at mcjty.meecreeps.actions.workers.ChopTreeActionWorker.lambda$tick$0(ChopTreeActionWorker.java:128)
	at mcjty.meecreeps.actions.workers.ChopTreeActionWorker$$Lambda$1669/1721979849.accept(Unknown Source)
	at mcjty.meecreeps.actions.workers.WorkerHelper.navigateTo(WorkerHelper.java:399)
	at mcjty.meecreeps.actions.workers.ChopTreeActionWorker.tick(ChopTreeActionWorker.java:128)
	at mcjty.meecreeps.actions.workers.WorkerHelper.tick(WorkerHelper.java:506)
	at mcjty.meecreeps.entities.MeeCreepWorkerTask.func_75246_d(MeeCreepWorkerTask.java:69)
	at net.minecraft.entity.ai.EntityAITasks.func_75774_a(SourceFile:129)
	at net.minecraft.entity.EntityLiving.func_70626_be(EntityLiving.java:763)
	at net.minecraft.entity.EntityLivingBase.func_70636_d(EntityLivingBase.java:2350)
	at net.minecraft.entity.EntityLiving.func_70636_d(EntityLiving.java:577)
	at net.minecraft.entity.EntityLivingBase.func_70071_h_(EntityLivingBase.java:2170)
	at net.minecraft.entity.EntityLiving.func_70071_h_(EntityLiving.java:295)
	at net.minecraft.world.World.func_72866_a(World.java:1990)
	at net.minecraft.world.WorldServer.func_72866_a(WorldServer.java:831)
	at net.minecraft.world.World.func_72870_g(World.java:1952)

**Comment by McJty** [comment]
When you do what?

**Comment by Ioandar** [comment]
Sorry, I forgot to mention. Everytime I send a meecreep to cut a tree and a nature-berrybush is near

**Comment by maxell45146** [comment]
Similar issue with using the MeeCreeps to cut down a darkwood tree from Twilight Forest, seems like it got to the leaves and the leaves of the tree are missing a property that meecreeps need.

**Comment by danielm59** [comment]
Get a similar crash when meecreeps cut down trees near slurpies dongles bushs
