### ISSUE TITLE
Summoning a Meecreep freezes Minecraft for a few seconds

### ISSUE THREAD

**Issue by 1skandar** [McJty/MeeCreeps#43]
I'm still diagnosing the problem, so I'm not sure what the root cause is. That said, thing s used to be fine and now something has gone wonky. The game will freeze and spike memory usage briefly every time a Meecreep is summoned.

I've recently updated Forge to the recommended version (14.23.,3.2655) and I also just had a Java update (1.8.0.171 64 bit), either might be cause. And, well, as could any of a number of mod updates (this is my Modular Mayhem Reloaded modpack, btw). I haven't used a Meecreep in a couple of weeks now, so it is a bit of work working out the root cause.

Opening this issue just in case anyone else has noticed this problem and can contribute any info. I'll update as I investigate.

**Comment by 1skandar** [comment]
I suspect this is related to both #40 and #42. Having the Meecreep load and unload all dimensions on summon would certainly explain the lag spike I am seeing and could be behind the memory leak as well.

**Comment by McJty** [comment]
I will check this out. I don't see where I would be loading dimensions but if I do then that's indeed a bad situation. Thanks for investigating

**Comment by 1skandar** [comment]
If I might make a suggestion. All three bug reports have occurred within the last three weeks, which suggests two possible culprits. I'd say something introduced in either the latest McJtyLib or, possibly, something that has changed in the latest Forge build for 1.12.2. That is the only thing that I can think of, as I have been using the current build of Meecreeps with no problems...and that hasn't updated.

**Comment by McJty** [comment]
Can you tell me when exactly this occurs? I mean you right click the spawn cube and then at which point does the lag start?

**Comment by 1skandar** [comment]
Pretty much immediately. The Meecreep fails to spawn for a few seconds and during that time there is a massive lag spike, and the console starts throwing "Couldn't keep up!" warnings. You can sort of move around and do other things while waiting, although everything is running really slow.  After a bit the Meecreep finally summons and the lag dies down. I have also noticed the amount of memory that Java is using also balloons at the same time, and then idles back down again, although it also appears to "leak" a bit, as the memory doesn't fully fall back to pre-summon levels.

**Comment by 1skandar** [comment]
/creep_list output nothing. /creep_clear output "Cleared 0 active operations" 

I did notice this:
https://pastebin.com/kaG16zat

When summoning a Meecreep you can watch the console and see it load every dimension in the pack and then unload them and then reload them, and unload them, and do it again for a total of five times before the Meecreep is actually summoned.

**Comment by 1skandar** [comment]
Ok, I've sort of found the problem. I backdated Forge to version 14.23.2.2628 (released March 17th) and the problem is NOT present. So, somewhere between that version of Forge and the latest recommended (14.23.3.2655) something changed in Forge that has broken something. Um, I got a bit of time, I'll try to run down the specific update that broke things.

**Comment by fraenkelc** [comment]
In the stacktrace from  #42 the dimension is loaded from here: 
```
        at mcjty.lib.varia.TeleportationTools.getWorldForDimension(TeleportationTools.java:48)
        at mcjty.meecreeps.actions.ServerActionManager.findMeeCreep(ServerActionManager.java:247)
        at mcjty.meecreeps.actions.ServerActionManager.tick(ServerActionManager.java:263)
```

which corresponds to these lines
https://github.com/McJty/MeeCreeps/blob/cadd39e5566b4d39e4998280475a4ec4944241d3/src/main/java/mcjty/meecreeps/actions/ServerActionManager.java#L244-L253

**Comment by 1skandar** [comment]
Yeah, and I'd guess that is combining with whatever change was made to Forge in version 2647. If you are capable of backdating your Forge down to  14.23.2.2646 that will solve your issue until McJty can get to it.

**Comment by McJty** [comment]
Thanks for the investigation. I'll see what I can do on my side soon. But currently busy with a rework of McJtyLib

**Comment by McJty** [comment]
Are people having this problem using sponge? Does it also happen without sponge/

**Comment by McJty** [comment]
I may have a solution to at least improve the behaviour of this
